# Generated by Django 4.1 on 2022-11-10 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_transaction_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='account',
            new_name='account_number',
        ),
    ]
